#!/bin/sh
export JAVA_HOME=/opt/java
export JAVA_OPTIONS="-Djava.security.egd=file:/dev/./urandom"
export PATH=$JAVA_HOME/bin:$PATH

GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/glassfish4/glassfish"}

case "$1" in
start)
    $GLASSFISH_HOME/bin/asadmin start-domain >/dev/null
    ;;
stop)
    $GLASSFISH_HOME/bin/asadmin stop-domain >/dev/null
    ;;
restart)
    $GLASSFISH_HOME/bin/asadmin restart-domain >/dev/null
    ;;
\*)
    echo "usage: $0 (start|stop|restart|help)"
esac